name: "Playwright Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  BASE_URL: http://localhost:4321

jobs:
  ##################################################################
  # Run basic playwright validation tests, that all content appears
  ##################################################################
  site-validation:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Start Astro preview server
        run: npx serve dist -l 4321 &

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:4321

      - name: Run Playwright tests
        env:
          BASE_URL: http://localhost:4321
        run: npx playwright test

      - name: Stop preview server
        if: always()
        run: |
          kill $(cat astro.pid) || true